version: "3"
services:
        mysql-db:
                image: mysql:latest
                environment:
                        MYSQL_ROOT_PASSWORD: admin123
                        MYSQL_DATABASE: final_java_backend
                        MYSQL_USER: admin
                        MYSQL_PASSWORD: admin123
                ports:
                        - "3306:3306"
