server:
  port: 8099

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/final_java_backend
    username: root
    password: admin123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
#    hibernate:
#      ddl-auto: create
    show-sql: true