server:
  port: 8099

spring:
  datasource:
    url: jdbc:mysql://localhost:3360/final_java_backend?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true